# Generated by Django 3.2.8 on 2021-11-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211112_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Executing', 'Executing'), ('Done', 'Done')], default='Created', max_length=9),
        ),
    ]
