# Generated by Django 3.2.8 on 2021-11-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_announcement_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='user',
            new_name='owner',
        ),
    ]
