# Generated by Django 3.2.8 on 2021-11-13 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_announcement_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_executor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
