# Generated by Django 3.2.8 on 2021-11-13 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211113_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='executor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='executor_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
