# Generated by Django 3.2.8 on 2021-11-13 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211113_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
